checking state change
jstan-isch/spring-petclinic pull request #4
Opened 2022-09-28 12:11 UTC by jstan-isch

2022-09-28 12:18 UTC, jstan-isch reviewed
testing comment for review

2022-09-28 12:29 UTC, jstan-isch reviewed
testing for request changes

2022-09-28 12:30 UTC, debechi requested changes
see the requested changes

2022-09-28 12:32 UTC, debechi approved these changes
Testing Approved

2022-12-28 14:23 UTC, closed without merging

2022-12-28 14:24 UTC, jstan-isch commented
nothing